# Generated by Django 4.2.5 on 2023-09-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_pretynum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PretyNum',
            new_name='PrettyNum',
        ),
    ]
